// <auto-generated>
// Company Supplier — lokalisierte UI-Strings (DE/EN/FR/ES).
//
// NICHT VON HAND BEARBEITEN. Quelle: docs/localization/strings.json.
// Regenerieren: node _tools/gen-localization.js
// Jede Zeile zeigt alle vier Sprachen: Loc.T(en, de, fr, es) waehlt nach Spielsprache (Loc.cs);
// Englisch ist der Fallback. Format-Eintraege (mit {0}/{1}/…) sind Methoden mit string.Format —
// die Platzhalter sind in allen Sprachen identisch (per Generator geprueft).
//
// Produkt-/Materialnamen kommen aus der Spiel-Lokalisierung (ProtoDisplayName) und stehen NICHT hier.
// </auto-generated>
namespace CompanySupplier.Localization
{
    /// <summary>Zentrale, lokalisierte UI-Texttabelle des Mods. Zugriff ueber <c>L.&lt;Key&gt;</c>.</summary>
    internal static class L
    {

        // ---- Common ----
        public static string Common_Set => Loc.T("Set", "Setzen", "Appliquer", "Aplicar");
        public static string Common_Reset => Loc.T("Reset", "Zurücksetzen", "Réinit.", "Restablecer");
        public static string Common_InvalidNumber(object a0) => string.Format(Loc.T("Invalid number: \"{0}\"", "Ungültige Zahl: \"{0}\"", "Nombre invalide : « {0} »", "Número no válido: \"{0}\""), a0);

        // ---- Unit ----
        public static string Unit_Pieces => Loc.T("pcs", "Stück", "unités", "uds.");

        // ---- Tab ----
        public static string Tab_Ressourcen => Loc.T("Resources", "Ressourcen", "Ressources", "Recursos");
        public static string Tab_Allgemein => Loc.T("General", "Allgemein", "Général", "General");
        public static string Tab_Umwelt => Loc.T("Environment", "Umwelt", "Environnement", "Medioambiente");
        public static string Tab_Weltkarte => Loc.T("World Map", "Weltkarte", "Carte du monde", "Mapa mundial");
        public static string Tab_Erzeugung => Loc.T("Generation", "Erzeugung", "Génération", "Generación");
        public static string Tab_WerftFlotte => Loc.T("Shipyard & Fleet", "Werft & Flotte", "Chantier & flotte", "Astillero y flota");
        public static string Tab_Fahrzeuge => Loc.T("Vehicles", "Fahrzeuge", "Véhicules", "Vehículos");
        public static string Tab_Gelaende => Loc.T("Terrain", "Gelände", "Terrain", "Terreno");
        public static string Tab_Wetter => Loc.T("Weather", "Wetter", "Météo", "Clima");
        public static string Tab_Profil => Loc.T("Profile", "Profil", "Profil", "Perfil");

        // ---- Res ----
        public static string Res_TitleGive => Loc.T("Add Resources to Storage", "Ressourcen ins Lager geben", "Ajouter des ressources au stockage", "Añadir recursos al almacén");
        public static string Res_TitleTool => Loc.T("Storage Tool", "Lager-Werkzeug", "Outil de stockage", "Herramienta de almacén");
        public static string Res_Product => Loc.T("Product", "Produkt", "Produit", "Producto");
        public static string Res_Quantity => Loc.T("Amount", "Menge", "Quantité", "Cantidad");
        public static string Res_QuantityValue(object a0) => string.Format(Loc.T("Amount: {0} pcs", "Menge: {0} Stück", "Quantité : {0} unités", "Cantidad: {0} uds."), a0);
        public static string Res_AddProduct => Loc.T("Add Product", "Produkt hinzufügen", "Ajouter le produit", "Añadir producto");
        public static string Res_AddProductTip => Loc.T("Adds the set amount of the selected product to central storage.", "Legt die eingestellte Menge des gewählten Produkts ins zentrale Lager.", "Place la quantité définie du produit sélectionné dans le stockage central.", "Añade la cantidad indicada del producto elegido al almacén central.");
        public static string Res_AddAll => Loc.T("Add ALL Products", "ALLE Produkte hinzufügen", "Ajouter TOUS les produits", "Añadir TODOS los productos");
        public static string Res_AddAllTip => Loc.T("Adds the set amount of EVERY spawnable product to storage.", "Legt die eingestellte Menge von JEDEM spawnbaren Produkt ins Lager.", "Place la quantité définie de CHAQUE produit générable dans le stockage.", "Añade la cantidad indicada de CADA producto generable al almacén.");
        public static string Res_FillAll => Loc.T("Fill ALL storages (caution!)", "ALLE Lager füllen (Vorsicht!)", "Remplir TOUS les stockages (prudence !)", "Llenar TODOS los almacenes (¡ojo!)");
        public static string Res_FillAllTip => Loc.T("CAUTION: Instantly sets ALL storages in the game to 'always full' — every storage is filled completely with its product and stays full. Not cleanly reversible (original contents are overwritten). For safety it's two-step: click once to arm, then again to trigger. For individual storages, use the 'Fill storage' (click) tool instead.", "VORSICHT: Setzt ALLE Lager im Spiel sofort auf 'immer voll' — jedes Lager wird komplett mit seinem Produkt gefüllt und bleibt voll. Nicht sauber rückgängig (Originalinhalt überschrieben). Zur Sicherheit zweistufig: erst klicken zum Scharfschalten, dann nochmal zum Auslösen. Für einzelne Lager stattdessen den 'Lager-Zauberstab' (anklicken) nutzen.", "ATTENTION : met TOUS les stockages du jeu sur « toujours plein » — chaque stockage est aussitôt rempli de son produit et le reste. Non réversible proprement (contenu d'origine écrasé). Par sécurité, action en deux temps : un clic pour armer, un second pour déclencher. Pour un stockage précis, utilisez plutôt la « baguette de stockage » (à cliquer).", "CUIDADO: pone al instante TODOS los almacenes del juego en «siempre lleno»; cada almacén se llena por completo con su producto y permanece lleno. No se puede deshacer limpiamente (se sobrescribe el contenido original). Por seguridad va en dos pasos: pulsa una vez para armar y otra para ejecutar. Para almacenes concretos usa mejor la «varita de almacén» (clic).");
        public static string Res_FillWand => Loc.T("Fill storage (click)", "Lager füllen (anklicken)", "Remplir un stockage (à cliquer)", "Llenar almacén (clic)");
        public static string Res_FillWandTip => Loc.T("Active: clicking a single storage in the world fills it permanently (KeepFull, click = on/off). Only ONE storage tool at a time — automatically turns off 'Empty storage'.", "Aktiv: ein einzelnes Lager im Spiel anklicken füllt es dauerhaft (KeepFull, klick = an/aus). Nur EIN Lager-Werkzeug gleichzeitig — schaltet 'Lager leeren' automatisch ab.", "Actif : cliquer sur un stockage précis dans le jeu le remplit en continu (KeepFull, clic = marche/arrêt). Un seul outil de stockage à la fois — désactive automatiquement « Vider un stockage ».", "Activo: al hacer clic en un almacén del juego se llena de forma permanente (mantener lleno; clic = on/off). Solo UNA herramienta de almacén a la vez — desactiva «Vaciar almacén» automáticamente.");
        public static string Res_EmptyWand => Loc.T("Empty storage (click)", "Lager leeren (anklicken)", "Vider un stockage (à cliquer)", "Vaciar almacén (clic)");
        public static string Res_EmptyWandTip => Loc.T("Active: clicking a single storage in the world empties it ONCE (contents out) — e.g. for nuclear waste. The storage then runs normally afterwards (is NOT kept permanently empty). Only ONE storage tool at a time — automatically turns off 'Fill storage'.", "Aktiv: ein einzelnes Lager im Spiel anklicken leert es EINMALIG (Inhalt raus) — z. B. für Atommüll. Das Lager läuft danach normal weiter (wird NICHT dauerhaft leer gehalten). Nur EIN Lager-Werkzeug gleichzeitig — schaltet 'Lager füllen' automatisch ab.", "Actif : cliquer sur un stockage précis dans le jeu le vide une seule fois (contenu retiré) — par ex. pour les déchets nucléaires. Le stockage reprend ensuite son fonctionnement normal (il n'est PAS maintenu vide). Un seul outil de stockage à la fois — désactive automatiquement « Remplir un stockage ».", "Activo: al hacer clic en un almacén del juego se vacía UNA sola vez (se retira el contenido); p. ej. para residuos nucleares. Después el almacén sigue funcionando con normalidad (NO se mantiene vacío). Solo UNA herramienta de almacén a la vez — desactiva «Llenar almacén» automáticamente.");
        public static string Res_StatusAdded(object a0, object a1) => string.Format(Loc.T("Added {0}x {1}", "{0}x {1} hinzugefügt", "{0}x {1} ajouté", "{0}x {1} añadido"), a0, a1);
        public static string Res_StatusAddedAll(object a0) => string.Format(Loc.T("Added {0}x of ALL products", "{0}x von ALLEN Produkten hinzugefügt", "{0}x de TOUS les produits ajoutés", "{0}x de TODOS los productos añadido"), a0);
        public static string Res_StatusConfirm => Loc.T("Sure? Click again to confirm — fills ALL storages.", "Sicher? Nochmal klicken zum Bestätigen — füllt ALLE Lager.", "Sûr ? Cliquez à nouveau pour confirmer — remplit TOUS les stockages.", "¿Seguro? Pulsa otra vez para confirmar: llena TODOS los almacenes.");
        public static string Res_StatusGodOn => Loc.T("ALL storages set to god mode (instantly filled)", "ALLE Lager auf Gottmodus gesetzt (sofort komplett gefüllt)", "TOUS les stockages en mode dieu (aussitôt remplis)", "TODOS los almacenes en modo dios (llenos al instante)");
        public static string Res_StatusGodOff => Loc.T("God mode for all storages OFF (contents remain)", "Gottmodus für alle Lager AUS (Lagerinhalt bleibt)", "Mode dieu DÉSACTIVÉ pour tous les stockages (contenu conservé)", "Modo dios de almacenes DESACTIVADO (se conserva el contenido)");
        public static string Res_StatusFillWandOn => Loc.T("Fill storage ON — click a storage in the world", "Lager füllen AN — ein Lager im Spiel anklicken", "Remplissage ACTIVÉ — cliquez sur un stockage dans le jeu", "Llenar almacén ACTIVADO — haz clic en un almacén");
        public static string Res_StatusEmptyWandOn => Loc.T("Empty storage ON — click a storage in the world", "Lager leeren AN — ein Lager im Spiel anklicken", "Vidage ACTIVÉ — cliquez sur un stockage dans le jeu", "Vaciar almacén ACTIVADO — haz clic en un almacén");
        public static string Res_StatusFillWandOff => Loc.T("Fill storage OFF", "Lager füllen AUS", "Remplissage de stockage DÉSACTIVÉ", "Llenar almacén DESACTIVADO");
        public static string Res_StatusEmptyWandOff => Loc.T("Empty storage OFF", "Lager leeren AUS", "Vidage de stockage DÉSACTIVÉ", "Vaciar almacén DESACTIVADO");
        public static string Res_StatusFillWandUnavail => Loc.T("Storage tool (fill) not available", "Lager-Werkzeug (füllen) nicht verfügbar", "Outil de stockage (remplir) indisponible", "Herramienta de almacén (llenar) no disponible");
        public static string Res_StatusEmptyWandUnavail => Loc.T("Storage tool (empty) not available", "Lager-Werkzeug (leeren) nicht verfügbar", "Outil de stockage (vider) indisponible", "Herramienta de almacén (vaciar) no disponible");
        public static string Res_TitleFavorites => Loc.T("Favourites", "Favoriten", "Favoris", "Favoritos");
        public static string Res_PinFavorite => Loc.T("★ Favourite", "★ Favorit", "★ Favori", "★ Favorito");
        public static string Res_ThroughputTitle => Loc.T("Storage throughput", "Lager-Durchsatz", "Débit de stockage", "Rendimiento de almacén");
        public static string Res_ThroughputTip => Loc.T("Scales the transfer throughput of all storage types.", "Skaliert den Transfer-Durchsatz aller Lager-Typen.", "Met à l'échelle le débit de transfert de tous les types de stockage.", "Escala el rendimiento de transferencia de todos los tipos de almacén.");
        public static string Res_StatusThroughput(object a0) => string.Format(Loc.T("Storage throughput x{0}", "Lager-Durchsatz x{0}", "Débit de stockage x{0}", "Rendimiento de almacén x{0}"), a0);
        public static string Res_StatusThroughputReset => Loc.T("Storage throughput reset", "Lager-Durchsatz zurückgesetzt", "Débit de stockage réinitialisé", "Rendimiento de almacén restablecido");
        public static string Res_StatusFavAdded(object a0) => string.Format(Loc.T("{0} added to favourites", "{0} zu Favoriten hinzugefügt", "{0} ajouté aux favoris", "{0} añadido a favoritos"), a0);
        public static string Res_StatusFavRemoved(object a0) => string.Format(Loc.T("{0} removed from favourites", "{0} aus Favoriten entfernt", "{0} retiré des favoris", "{0} eliminado de favoritos"), a0);

        // ---- Gen ----
        public static string Gen_TitleCreative => Loc.T("Creative Mode", "Kreativmodus", "Mode créatif", "Modo creativo");
        public static string Gen_TitleDespiteShortage => Loc.T("Runs Despite Shortage", "Läuft trotz Mangel", "Fonctionne malgré la pénurie", "Funciona pese a la escasez");
        public static string Gen_TitleBuildOps => Loc.T("Build & Operation", "Bau & Betrieb", "Construction & exploitation", "Construcción y operación");
        public static string Gen_TitleSpeed => Loc.T("Game Speed", "Spielgeschwindigkeit", "Vitesse de jeu", "Velocidad de juego");
        public static string Gen_TitleSourceSink => Loc.T("Infinite Source/Sink", "Unendlich-Quelle/Senke", "Source/puits infini", "Fuente/sumidero infinitos");
        public static string Gen_TitleGodTool => Loc.T("God Tool (World Click)", "God-Werkzeug (Welt-Klick)", "Outil dieu (clic sur le monde)", "Herramienta dios (clic en el mundo)");
        public static string Gen_TitlePopulation => Loc.T("Population & Supply", "Bevölkerung & Versorgung", "Population & approvisionnement", "Población y suministro");
        public static string Gen_TitleAddPopulation => Loc.T("Add Population", "Bevölkerung hinzufügen", "Ajouter de la population", "Añadir población");
        public static string Gen_TitleResearch => Loc.T("Research", "Forschung", "Recherche", "Investigación");
        public static string Gen_TitleAddUnity => Loc.T("Add Unity", "Unity hinzufügen", "Ajouter de l'Unity", "Añadir Unity");
        public static string Gen_NoPower => Loc.T("No power needed", "Kein Strom nötig", "Aucune électricité requise", "Sin electricidad");
        public static string Gen_NoPowerTip => Loc.T("Machines keep running even without enough power.", "Maschinen laufen weiter, auch wenn nicht genug Strom da ist.", "Les machines continuent de tourner même sans électricité suffisante.", "Las máquinas siguen funcionando aunque no haya electricidad suficiente.");
        public static string Gen_NoWorkers => Loc.T("No workers needed", "Keine Arbeiter nötig", "Aucun ouvrier requis", "Sin trabajadores");
        public static string Gen_NoWorkersTip => Loc.T("Buildings operate without assigned workers.", "Gebäude arbeiten ohne zugewiesene Arbeiter.", "Les bâtiments fonctionnent sans ouvriers affectés.", "Los edificios funcionan sin trabajadores asignados.");
        public static string Gen_NoComputing => Loc.T("No Computing needed", "Kein Computing nötig", "Aucun Computing requis", "Sin Computing");
        public static string Gen_NoComputingTip => Loc.T("Machines run without sufficient Computing.", "Maschinen laufen ohne ausreichendes Computing.", "Les machines tournent sans Computing suffisant.", "Las máquinas funcionan sin Computing suficiente.");
        public static string Gen_NoUnity => Loc.T("No Unity needed", "Keine Unity nötig", "Aucune Unity requise", "Sin Unity");
        public static string Gen_NoUnityTip => Loc.T("Actions/buildings that require Unity run without it.", "Aktionen/Gebäude, die Unity verlangen, laufen ohne Unity.", "Les actions/bâtiments qui exigent de l'Unity fonctionnent sans Unity.", "Las acciones/edificios que requieren Unity funcionan sin ella.");
        public static string Gen_NoFood => Loc.T("No food needed", "Keine Lebensmittel nötig", "Aucune nourriture requise", "Sin alimentos");
        public static string Gen_NoFoodTip => Loc.T("No hunger/supply penalty when food is missing.", "Keine Hunger-/Versorgungs-Strafe bei fehlenden Lebensmitteln.", "Aucune pénalité de faim/approvisionnement en cas de manque de nourriture.", "Sin penalización por hambre/suministro cuando faltan alimentos.");
        public static string Gen_InstaBuild => Loc.T("Instant build", "Sofortbau", "Construction instantanée", "Construcción instantánea");
        public static string Gen_InstaBuildTip => Loc.T("Buildings, research, upgrades and repairs complete instantly.", "Gebäude, Forschung, Upgrades und Reparaturen werden sofort fertig.", "Bâtiments, recherche, améliorations et réparations se terminent instantanément.", "Los edificios, la investigación, las mejoras y las reparaciones se completan al instante.");
        public static string Gen_NoFuel => Loc.T("No fuel consumption", "Kein Treibstoffverbrauch", "Aucune consommation de carburant", "Sin consumo de combustible");
        public static string Gen_NoFuelTip => Loc.T("Vehicles no longer consume fuel.", "Fahrzeuge verbrauchen keinen Treibstoff mehr.", "Les véhicules ne consomment plus de carburant.", "Los vehículos ya no consumen combustible.");
        public static string Gen_NoMaintenance => Loc.T("Disable maintenance", "Wartung deaktivieren", "Désactiver la maintenance", "Desactivar mantenimiento");
        public static string Gen_NoMaintenanceTip => Loc.T("No maintenance consumption; existing damage is repaired.", "Kein Wartungsverbrauch; vorhandene Schäden werden repariert.", "Aucune consommation de maintenance ; les dégâts existants sont réparés.", "Sin consumo de mantenimiento; se reparan los daños existentes.");
        public static string Gen_Master => Loc.T("Creative mode (all at once)", "Kreativmodus (alles auf einmal)", "Mode créatif (tout d'un coup)", "Modo creativo (todo a la vez)");
        public static string Gen_MasterTip => Loc.T("Enables in one go: no power/workers/Computing/Unity/food needed, instant build, no fuel, no maintenance.", "Aktiviert auf einen Schlag: kein Strom/Arbeiter/Computing/Unity/Lebensmittel nötig, Sofortbau, kein Treibstoff, keine Wartung.", "Active d'un seul coup : aucune électricité/ouvrier/Computing/Unity/nourriture requis, construction instantanée, aucun carburant, aucune maintenance.", "Activa de golpe: sin electricidad/trabajadores/Computing/Unity/alimentos, construcción instantánea, sin combustible y sin mantenimiento.");
        public static string Gen_Uncapped => Loc.T("Uncapped (as fast as the CPU can go)", "Uncapped (so schnell wie die CPU kann)", "Sans limite (selon le CPU)", "Sin límite (tan rápido como la CPU)");
        public static string Gen_UncappedTip => Loc.T("Removes the sim speed limit — the simulation runs as fast as your machine allows.", "Hebt das Sim-Geschwindigkeitslimit auf — die Simulation läuft so schnell, wie der Rechner erlaubt.", "Supprime la limite de vitesse de simulation — la simulation tourne aussi vite que la machine le permet.", "Elimina el límite de velocidad de la simulación — esta corre tan rápido como permita el equipo.");
        public static string Gen_SourceSink => Loc.T("Unlock in build toolbar", "In Bau-Toolbar freischalten", "Débloquer dans la barre de construction", "Desbloquear en la barra de construcción");
        public static string Gen_SourceSinkTip => Loc.T("Unlocks the built-in cheat building: infinite source for any product + bottomless sink. Then place it normally from the build toolbar.", "Schaltet das eingebaute Cheat-Gebäude frei: unendliche Quelle für jedes Produkt + bodenlose Senke. Danach ganz normal über die Bau-Toolbar platzieren.", "Débloque le bâtiment de triche intégré : source infinie de n'importe quel produit + puits sans fond. Placez-le ensuite normalement via la barre de construction.", "Desbloquea el edificio-truco integrado: fuente infinita de cualquier producto y sumidero sin fondo. Luego se coloca con normalidad desde la barra de construcción.");
        public static string Gen_GodWand => Loc.T("God tool active", "God-Werkzeug aktiv", "Outil dieu actif", "Herramienta dios activa");
        public static string Gen_GodWandTip => Loc.T("While active: left-click a shipyard, cargo depot or vehicle to instantly refuel it fully.", "Solange aktiv: Linksklick auf eine Werft, ein Cargo-Depot oder ein Fahrzeug tankt es sofort voll.", "Tant qu'il est actif : un clic gauche sur un chantier naval, un dépôt de fret ou un véhicule fait aussitôt le plein.", "Mientras esté activa: haz clic izquierdo en un astillero, un depósito de carga o un vehículo para repostarlo al instante.");
        public static string Gen_Diseases => Loc.T("Disable diseases", "Krankheiten deaktivieren", "Désactiver les maladies", "Desactivar enfermedades");
        public static string Gen_DiseasesTip => Loc.T("Any newly appearing outbreak is automatically ended at once.", "Jede neu auftretende Seuche wird automatisch sofort beendet.", "Chaque nouvelle épidémie est automatiquement stoppée aussitôt.", "Cada nueva epidemia que aparezca se detiene automáticamente al instante.");
        public static string Gen_Happiness => Loc.T("Max supply happiness", "Versorgungs-Zufriedenheit max.", "Satisfaction d'approvisionnement max.", "Satisfacción de suministro máx.");
        public static string Gen_HappinessTip => Loc.T("Keeps settlement happiness from supply/food permanently at maximum.", "Hält die Siedlungs-Zufriedenheit aus Versorgung/Lebensmitteln dauerhaft auf Maximum.", "Maintient en permanence au maximum la satisfaction de la colonie liée à l'approvisionnement/la nourriture.", "Mantiene siempre al máximo la satisfacción del asentamiento por suministro/alimentos.");
        public static string Gen_KeepUnity => Loc.T("Keep Unity full", "Unity voll halten", "Maintenir l'Unity au max", "Mantener Unity al máximo");
        public static string Gen_KeepUnityTip => Loc.T("Automatically tops up Unity to its cap every day.", "Füllt die Unity-Punkte täglich automatisch bis zur Kapazität auf.", "Remplit automatiquement l'Unity jusqu'à sa capacité chaque jour.", "Rellena automáticamente la Unity hasta su capacidad cada día.");
        public static string Gen_SpeedResetTip => Loc.T("Back to normal speed.", "Zurück auf Normalgeschwindigkeit.", "Retour à la vitesse normale.", "Vuelve a la velocidad normal.");
        public static string Gen_Speed5Tip => Loc.T("Simulation 5x.", "Simulation 5-fach.", "Simulation x5.", "Simulación a 5x.");
        public static string Gen_Speed10Tip => Loc.T("Simulation 10x.", "Simulation 10-fach.", "Simulation x10.", "Simulación a 10x.");
        public static string Gen_Speed20Tip => Loc.T("Simulation 20x (CPU-dependent).", "Simulation 20-fach (CPU-abhängig).", "Simulation x20 (selon le CPU).", "Simulación a 20x (según la CPU).");
        public static string Gen_ResearchFinish => Loc.T("Finish current research", "Aktuelle Forschung abschließen", "Terminer la recherche en cours", "Completar investigación actual");
        public static string Gen_ResearchFinishTip => Loc.T("Completes the currently running research instantly.", "Beendet die aktuell laufende Forschung sofort.", "Termine instantanément la recherche actuellement en cours.", "Finaliza al instante la investigación en curso.");
        public static string Gen_ResearchUnlockAll => Loc.T("Unlock all research", "Alle Forschung freischalten", "Débloquer toute la recherche", "Desbloquear toda la investigación");
        public static string Gen_ResearchUnlockAllTip => Loc.T("Unlocks the entire research tree.", "Schaltet den kompletten Forschungsbaum frei.", "Débloque l'intégralité de l'arbre de recherche.", "Desbloquea el árbol de investigación completo.");
        public static string Gen_StatusCreativeOn => Loc.T("Creative mode ON", "Kreativmodus AN", "Mode créatif ACTIVÉ", "Modo creativo ACTIVADO");
        public static string Gen_StatusCreativeOff => Loc.T("Creative mode OFF", "Kreativmodus AUS", "Mode créatif DÉSACTIVÉ", "Modo creativo DESACTIVADO");
        public static string Gen_StatusSpeed(object a0) => string.Format(Loc.T("Game speed: {0}x", "Spielgeschwindigkeit: {0}x", "Vitesse de jeu : {0}x", "Velocidad de juego: {0}x"), a0);
        public static string Gen_StatusSourceSinkOn => Loc.T("Source/sink unlocked in the build toolbar", "Quelle/Senke in der Bau-Toolbar freigeschaltet", "Source/puits débloqué dans la barre de construction", "Fuente/sumidero desbloqueados en la barra de construcción");
        public static string Gen_StatusSourceSinkOff => Loc.T("Source/sink disabled", "Quelle/Senke deaktiviert", "Source/puits désactivé", "Fuente/sumidero desactivados");
        public static string Gen_StatusGodWandUnavail => Loc.T("God tool not available", "God-Werkzeug nicht verfügbar", "Outil dieu indisponible", "Herramienta dios no disponible");
        public static string Gen_StatusGodWandOn => Loc.T("God tool ON — click a shipyard/depot/vehicle", "God-Werkzeug AN — Werft/Depot/Fahrzeug anklicken", "Outil dieu ACTIVÉ — cliquez sur chantier/dépôt/véhicule", "Herramienta dios ACTIVADA — haz clic en astillero/depósito/vehículo");
        public static string Gen_StatusGodWandOff => Loc.T("God tool OFF", "God-Werkzeug AUS", "Outil dieu DÉSACTIVÉ", "Herramienta dios DESACTIVADA");
        public static string Gen_StatusResearchFinished => Loc.T("Current research completed", "Aktuelle Forschung abgeschlossen", "Recherche en cours terminée", "Investigación actual completada");
        public static string Gen_StatusResearchUnlocked => Loc.T("Entire research tree unlocked", "Kompletter Forschungsbaum freigeschaltet", "Arbre de recherche entièrement débloqué", "Árbol de investigación completo desbloqueado");
        public static string Gen_SetPopulation => Loc.T("Set population", "Bevölkerung setzen", "Définir la population", "Establecer población");
        public static string Gen_SetPopulationTip => Loc.T("Sets total population to the entered value.", "Setzt die Gesamtbevölkerung auf den eingegebenen Wert.", "Définit la population totale sur la valeur saisie.", "Establece la población total en el valor introducido.");
        public static string Gen_ResearchUnlockAvailable => Loc.T("Unlock available research", "Verfügbare Forschung freischalten", "Débloquer la recherche disponible", "Desbloquear investigación disponible");
        public static string Gen_ResearchUnlockAvailableTip => Loc.T("Unlocks all currently reachable research nodes.", "Schaltet alle aktuell erreichbaren Forschungsknoten frei.", "Débloque tous les nœuds de recherche actuellement accessibles.", "Desbloquea todos los nodos de investigación accesibles actualmente.");
        public static string Gen_ResearchUnlockRepeatable => Loc.T("Unlock repeatable research", "Wiederholbare Forschung freischalten", "Débloquer la recherche répétable", "Desbloquear investigación repetible");
        public static string Gen_ResearchUnlockRepeatableTip => Loc.T("Unlocks all repeatable research once.", "Schaltet alle wiederholbaren Forschungen einmal frei.", "Débloque une fois toutes les recherches répétables.", "Desbloquea una vez todas las investigaciones repetibles.");
        public static string Gen_ResearchIgnoreItems => Loc.T("Ignore item requirements", "Produkt-Voraussetzungen ignorieren", "Ignorer les prérequis en produits", "Ignorar requisitos de productos");
        public static string Gen_ResearchIgnoreItemsTip => Loc.T("Research ignores required products/conditions.", "Forschung ignoriert benötigte Produkte/Bedingungen.", "La recherche ignore les produits/conditions requis.", "La investigación ignora los productos/condiciones requeridos.");
        public static string Gen_ResearchIgnoreParents => Loc.T("Ignore parent requirements", "Eltern-Voraussetzungen ignorieren", "Ignorer les prérequis parents", "Ignorar requisitos previos");
        public static string Gen_ResearchIgnoreParentsTip => Loc.T("Every node is researchable without its predecessors.", "Jeder Knoten ist ohne seine Vorgänger forschbar.", "Chaque nœud est disponible sans ses prédécesseurs.", "Cada nodo se puede investigar sin sus predecesores.");
        public static string Gen_TitleWorldgen => Loc.T("WorldGen fixes", "WorldGen-Fixes", "Correctifs WorldGen", "Correcciones de WorldGen");
        public static string Gen_WorldgenUnlock => Loc.T("Unlock locked seeds/radar", "Gesperrtes Saatgut/Radar freischalten", "Débloquer graines/radar verrouillés", "Desbloquear semillas/radar bloqueados");
        public static string Gen_WorldgenUnlockTip => Loc.T("Fixes the worldgen bug: unlocks sugar cane/poppy/corn seeds and radar 2.", "Behebt den WorldGen-Bug: schaltet Zuckerrohr-/Mohn-/Mais-Saatgut und Radar 2 frei.", "Corrige le bug worldgen : débloque les graines de canne à sucre/pavot/maïs et le radar 2.", "Corrige el error de worldgen: desbloquea semillas de caña de azúcar/amapola/maíz y radar 2.");
        public static string Gen_StatusPopulationSet(object a0) => string.Format(Loc.T("Population set to {0}", "Bevölkerung auf {0} gesetzt", "Population définie sur {0}", "Población establecida en {0}"), a0);
        public static string Gen_StatusWorldgen => Loc.T("WorldGen fixes applied", "WorldGen-Fixes angewendet", "Correctifs WorldGen appliqués", "Correcciones de WorldGen aplicadas");

        // ---- Erz ----
        public static string Erz_TitlePower => Loc.T("Free power (KW) per tick", "Gratis-Strom (KW) pro Tick", "Électricité gratuite (KW) par tick", "Electricidad gratis (KW) por tick");
        public static string Erz_TitleComputing => Loc.T("Free Computing (TFlops) per tick", "Gratis-Rechenleistung (TFlops) pro Tick", "Puissance de calcul gratuite (TFlops) par tick", "Computing gratis (TFlops) por tick");
        public static string Erz_TitleUnity => Loc.T("Free Unity per month", "Gratis-Unity pro Monat", "Unity gratuite par mois", "Unity gratis al mes");
        public static string Erz_Value => Loc.T("Value", "Wert", "Valeur", "Valor");
        public static string Erz_TitleFake => Loc.T("Fake consumption (display only)", "Fake-Verbrauch (nur Anzeige)", "Consommation factice (affichage)", "Consumo falso (solo visual)");
        public static string Erz_FakePower => Loc.T("Fake power consumption (MW)", "Fake-Strom-Verbrauch (MW)", "Consommation d'énergie factice (MW)", "Consumo de energía falso (MW)");
        public static string Erz_FakeComputing => Loc.T("Fake computing consumption (TFLOPS)", "Fake-Computing-Verbrauch (TFlops)", "Consommation de calcul factice (TFLOPS)", "Consumo de cómputo falso (TFLOPS)");

        // ---- Fzg ----
        public static string Fzg_TitleFuel => Loc.T("Fuel", "Treibstoff", "Carburant", "Combustible");
        public static string Fzg_TitleLimit => Loc.T("Vehicle Limit", "Fahrzeug-Limit", "Limite de véhicules", "Límite de vehículos");
        public static string Fzg_TitleTruckCap => Loc.T("Truck Capacity", "LKW-Kapazität", "Capacité des camions", "Capacidad de camión");
        public static string Fzg_TitleStats => Loc.T("Vehicle Stats (per type)", "Fahrzeug-Stats (pro Typ)", "Stats de véhicule (par type)", "Estadísticas de vehículo (por tipo)");
        public static string Fzg_TitleOverview => Loc.T("Overview", "Übersicht", "Aperçu", "Resumen");
        public static string Fzg_TitleTrain => Loc.T("Train Wagon Capacity", "Zug-Waggon-Kapazität", "Capacité des wagons", "Capacidad de vagón de tren");
        public static string Fzg_Fuel => Loc.T("Disable fuel consumption", "Treibstoff-Verbrauch abschalten", "Couper la consommation de carburant", "Desactivar consumo de combustible");
        public static string Fzg_FuelTip => Loc.T("Active = vehicles no longer consume fuel.", "Aktiv = Fahrzeuge verbrauchen keinen Treibstoff mehr.", "Actif = les véhicules ne consomment plus de carburant.", "Activo = los vehículos ya no consumen combustible.");
        public static string Fzg_LimitSet => Loc.T("Set limit", "Limit setzen", "Définir la limite", "Fijar límite");
        public static string Fzg_Speed => Loc.T("Speed", "Geschwindigkeit", "Vitesse", "Velocidad");
        public static string Fzg_LoadCap => Loc.T("Load capacity", "Ladekapazität", "Capacité de charge", "Capacidad de carga");
        public static string Fzg_Capacity => Loc.T("Capacity", "Kapazität", "Capacité", "Capacidad");
        public static string Fzg_Vehicle => Loc.T("Vehicle", "Fahrzeug", "Véhicule", "Vehículo");
        public static string Fzg_Wagon => Loc.T("Wagon", "Waggon", "Wagon", "Vagón");
        public static string Fzg_TruckResetTip => Loc.T("Removes the truck capacity multiplier (back to normal).", "Entfernt den LKW-Kapazitäts-Multiplikator (zurück auf Normal).", "Supprime le multiplicateur de capacité des camions (retour à la normale).", "Elimina el multiplicador de capacidad de camión (vuelve a lo normal).");
        public static string Fzg_StatsResetTip => Loc.T("Resets speed + capacity of the selected vehicle type to default.", "Setzt Geschwindigkeit + Kapazität des gewählten Fahrzeugtyps auf den Standard zurück.", "Réinitialise la vitesse et la capacité du type de véhicule sélectionné aux valeurs par défaut.", "Restablece la velocidad y la capacidad del tipo de vehículo elegido a sus valores por defecto.");
        public static string Fzg_TrainResetTip => Loc.T("Resets the capacity of the selected wagon type to default.", "Setzt die Kapazität des gewählten Waggon-Typs auf den Standard zurück.", "Réinitialise la capacité du type de wagon sélectionné à la valeur par défaut.", "Restablece la capacidad del tipo de vagón elegido a su valor por defecto.");
        public static string Fzg_LimitCurrent(object a0) => string.Format(Loc.T("Current limit: {0}", "Aktuelles Limit: {0}", "Limite actuelle : {0}", "Límite actual: {0}"), a0);
        public static string Fzg_MultiplierSummary(object a0, object a1) => string.Format(Loc.T("Current multiplier: {0} %  (x{1})", "Aktueller Multiplikator: {0} %  (x{1})", "Multiplicateur actuel : {0} %  (x{1})", "Multiplicador actual: {0} %  (x{1})"), a0, a1);
        public static string Fzg_TrucksUnavail => Loc.T("(truck types not available)", "(LKW-Typen nicht verfügbar)", "(types de camions indisponibles)", "(tipos de camión no disponibles)");
        public static string Fzg_NoTrucks => Loc.T("(no truck types found)", "(keine LKW-Typen gefunden)", "(aucun type de camion trouvé)", "(no se encontraron tipos de camión)");
        public static string Fzg_StatsUnavail => Loc.T("(vehicle stats not available)", "(Fahrzeug-Stats nicht verfügbar)", "(stats de véhicule indisponibles)", "(estadísticas de vehículo no disponibles)");
        public static string Fzg_StatSpeed(object a0) => string.Format(Loc.T("Speed: {0}", "Speed: {0}", "Vitesse : {0}", "Velocidad: {0}"), a0);
        public static string Fzg_StatSpeedDefault(object a0, object a1) => string.Format(Loc.T("Speed: {0} (default: {1})", "Speed: {0} (Standard: {1})", "Vitesse : {0} (défaut : {1})", "Velocidad: {0} (por defecto: {1})"), a0, a1);
        public static string Fzg_StatCap(object a0) => string.Format(Loc.T("Capacity: {0}", "Kapazität: {0}", "Capacité : {0}", "Capacidad: {0}"), a0);
        public static string Fzg_StatCapDefault(object a0, object a1) => string.Format(Loc.T("Capacity: {0} (default: {1})", "Kapazität: {0} (Standard: {1})", "Capacité : {0} (défaut : {1})", "Capacidad: {0} (por defecto: {1})"), a0, a1);
        public static string Fzg_StatCapNone => Loc.T("Capacity: —", "Kapazität: —", "Capacité : —", "Capacidad: —");
        public static string Fzg_OverviewCap(object a0) => string.Format(Loc.T("Cap {0}", "Kap {0}", "Cap {0}", "Cap {0}"), a0);
        public static string Fzg_OverviewCapNone => Loc.T("Cap —", "Kap —", "Cap —", "Cap —");
        public static string Fzg_TrainInfo(object a0, object a1) => string.Format(Loc.T("{0} — capacity: {1}", "{0} — Kapazität: {1}", "{0} — Capacité : {1}", "{0} — Capacidad: {1}"), a0, a1);
        public static string Fzg_TrainInfoDefault(object a0, object a1, object a2) => string.Format(Loc.T("{0} — capacity: {1} (default: {2})", "{0} — Kapazität: {1} (Standard: {2})", "{0} — Capacité : {1} (défaut : {2})", "{0} — Capacidad: {1} (por defecto: {2})"), a0, a1, a2);
        public static string Fzg_StatusLimit(object a0) => string.Format(Loc.T("Vehicle limit = {0}", "Fahrzeug-Limit = {0}", "Limite de véhicules = {0}", "Límite de vehículos = {0}"), a0);
        public static string Fzg_StatusSpeedSet(object a0, object a1) => string.Format(Loc.T("Speed {0} = {1}", "Geschwindigkeit {0} = {1}", "Vitesse {0} = {1}", "Velocidad {0} = {1}"), a0, a1);
        public static string Fzg_StatusCapSet(object a0, object a1) => string.Format(Loc.T("Capacity {0} = {1}", "Kapazität {0} = {1}", "Capacité {0} = {1}", "Capacidad {0} = {1}"), a0, a1);
        public static string Fzg_StatusStatsReset => Loc.T("Vehicle stats reset", "Fahrzeug-Stats zurückgesetzt", "Stats de véhicule réinitialisées", "Estadísticas de vehículo restablecidas");
        public static string Fzg_StatusWagonCapSet(object a0, object a1) => string.Format(Loc.T("Wagon capacity {0} = {1}", "Waggon-Kapazität {0} = {1}", "Capacité du wagon {0} = {1}", "Capacidad de vagón {0} = {1}"), a0, a1);
        public static string Fzg_StatusWagonReset => Loc.T("Wagon capacity reset", "Waggon-Kapazität zurückgesetzt", "Capacité du wagon réinitialisée", "Capacidad de vagón restablecida");

        // ---- Gel ----
        public static string Gel_Material => Loc.T("Material", "Material", "Matériau", "Material");
        public static string Gel_TitleOptions => Loc.T("Options", "Optionen", "Options", "Opciones");
        public static string Gel_TitleMarkers => Loc.T("Execute Markings Instantly", "Markierungen sofort ausführen", "Exécuter les marquages aussitôt", "Ejecutar marcas al instante");
        public static string Gel_TitleReserves => Loc.T("Reserves & Trees", "Reserven & Bäume", "Réserves & arbres", "Reservas y árboles");
        public static string Gel_Physics => Loc.T("Disable terrain physics", "Gelände-Physik deaktivieren", "Désactiver la physique du terrain", "Desactivar física del terreno");
        public static string Gel_PhysicsTip => Loc.T("Active = no physics simulation when mining/dumping (sharp edges).", "Aktiv = keine Physik-Simulation bei Abbau/Verfüllen (scharfe Kanten).", "Actif = aucune simulation physique lors de l'excavation/du remblai (bords nets).", "Activo = sin simulación física al excavar/rellenar (bordes definidos).");
        public static string Gel_IgnoreTower => Loc.T("Ignore tower markings", "Turm-Markierungen ignorieren", "Ignorer les marquages des tours", "Ignorar marcas de torre");
        public static string Gel_IgnoreTowerTip => Loc.T("Active = markings managed by mining towers are skipped during instant operations.", "Aktiv = von Minen-Türmen verwaltete Markierungen werden bei Sofort-Operationen übersprungen.", "Actif = les marquages gérés par les tours de mine sont ignorés lors des opérations instantanées.", "Activo = las marcas gestionadas por torres de mina se omiten en las operaciones instantáneas.");
        public static string Gel_Mine => Loc.T("Mine instantly", "Sofort abbauen", "Excaver aussitôt", "Excavar al instante");
        public static string Gel_MineTip => Loc.T("Completes all mining markings instantly (uses physics/tower options).", "Schließt alle Abbau-Markierungen sofort ab (nutzt Physik-/Turm-Optionen).", "Termine instantanément tous les marquages d'excavation (utilise les options physique/tour).", "Completa al instante todas las marcas de excavación (usa las opciones de física/torre).");
        public static string Gel_Dump => Loc.T("Dump instantly", "Sofort verfüllen", "Remblayer aussitôt", "Rellenar al instante");
        public static string Gel_DumpTip => Loc.T("Fills all dumping markings instantly with the selected material.", "Füllt alle Verfüll-Markierungen sofort mit dem gewählten Material.", "Remplit instantanément tous les marquages de remblai avec le matériau sélectionné.", "Rellena al instante todas las marcas de relleno con el material elegido.");
        public static string Gel_Change => Loc.T("Convert terrain", "Gelände umwandeln", "Convertir le terrain", "Convertir terreno");
        public static string Gel_ChangeTip => Loc.T("Converts the top material layer of the markings into the selected material (e.g. dirt for farms).", "Wandelt die oberste Materialschicht der Markierungen in das gewählte Material um (z. B. Erde für Farmen).", "Convertit la couche supérieure de matériau des marquages dans le matériau sélectionné (par ex. terre pour les fermes).", "Convierte la capa superior de material de las marcas en el material elegido (p. ej. tierra para granjas).");
        public static string Gel_FillWater => Loc.T("Refill groundwater", "Grundwasser auffüllen", "Remplir la nappe phréatique", "Rellenar agua subterránea");
        public static string Gel_FillWaterTip => Loc.T("Fills all groundwater reserves up to capacity.", "Füllt alle Grundwasser-Reserven bis zur Kapazität auf.", "Remplit toutes les réserves de nappe phréatique jusqu'à leur capacité.", "Rellena hasta su capacidad todas las reservas de agua subterránea.");
        public static string Gel_FillCrude => Loc.T("Refill crude oil", "Erdöl auffüllen", "Remplir le pétrole brut", "Rellenar petróleo");
        public static string Gel_FillCrudeTip => Loc.T("Fills all crude oil reserves up to capacity.", "Füllt alle Erdöl-Reserven bis zur Kapazität auf.", "Remplit toutes les réserves de pétrole brut jusqu'à leur capacité.", "Rellena hasta su capacidad todas las reservas de petróleo.");
        public static string Gel_PlantTrees => Loc.T("Plant trees", "Bäume pflanzen", "Planter des arbres", "Plantar árboles");
        public static string Gel_PlantTreesTip => Loc.T("Plants trees in the dumping markings.", "Pflanzt Bäume in den Verfüll-Markierungen.", "Plante des arbres dans les marquages de remblai.", "Planta árboles en las marcas de relleno.");
        public static string Gel_RemoveTrees => Loc.T("Remove trees", "Bäume entfernen", "Retirer les arbres", "Quitar árboles");
        public static string Gel_RemoveTreesTip => Loc.T("Removes all trees marked for removal.", "Entfernt alle zur Entfernung markierten Bäume.", "Retire tous les arbres marqués pour suppression.", "Elimina todos los árboles marcados para su tala.");

        // ---- Umw ----
        public static string Umw_TitlePollution => Loc.T("Pollution", "Verschmutzung", "Pollution", "Contaminación");
        public static string Umw_TitleSources => Loc.T("Individual Sources", "Einzelne Quellen", "Sources individuelles", "Fuentes individuales");
        public static string Umw_Air => Loc.T("Air pollution off", "Luftverschmutzung aus", "Pollution de l'air coupée", "Contaminación del aire desactivada");
        public static string Umw_AirTip => Loc.T("Factories/generators no longer emit air pollution.", "Fabriken/Generatoren stoßen keine Luftverschmutzung mehr aus.", "Les usines/générateurs ne rejettent plus de pollution atmosphérique.", "Las fábricas/generadores ya no emiten contaminación al aire.");
        public static string Umw_Water => Loc.T("Water pollution off", "Wasserverschmutzung aus", "Pollution de l'eau coupée", "Contaminación del agua desactivada");
        public static string Umw_WaterTip => Loc.T("No more water pollution.", "Keine Wasserverschmutzung mehr.", "Plus aucune pollution de l'eau.", "Ya no hay contaminación del agua.");
        public static string Umw_Landfill => Loc.T("Landfill pollution off", "Deponie-Verschmutzung aus", "Pollution des décharges coupée", "Contaminación de vertedero desactivada");
        public static string Umw_LandfillTip => Loc.T("Landfills no longer pollute the surroundings.", "Deponien verschmutzen die Umgebung nicht mehr.", "Les décharges ne polluent plus les alentours.", "Los vertederos ya no contaminan el entorno.");
        public static string Umw_Vehicles => Loc.T("Vehicle emissions off", "Fahrzeug-Abgase aus", "Émissions des véhicules coupées", "Emisiones de vehículos desactivadas");
        public static string Umw_VehiclesTip => Loc.T("Vehicles no longer emit exhaust.", "Fahrzeuge stoßen keine Abgase mehr aus.", "Les véhicules ne rejettent plus de gaz d'échappement.", "Los vehículos ya no emiten gases.");
        public static string Umw_Ships => Loc.T("Ship emissions off", "Schiffs-Abgase aus", "Émissions des navires coupées", "Emisiones de barcos desactivadas");
        public static string Umw_ShipsTip => Loc.T("Ships no longer emit exhaust.", "Schiffe stoßen keine Abgase mehr aus.", "Les navires ne rejettent plus de gaz d'échappement.", "Los barcos ya no emiten gases.");
        public static string Umw_Trains => Loc.T("Train emissions off", "Zug-Abgase aus", "Émissions des trains coupées", "Emisiones de trenes desactivadas");
        public static string Umw_TrainsTip => Loc.T("Trains no longer emit exhaust.", "Züge stoßen keine Abgase mehr aus.", "Les trains ne rejettent plus de gaz d'échappement.", "Los trenes ya no emiten gases.");
        public static string Umw_Master => Loc.T("No pollution (all off)", "Keine Verschmutzung (alles aus)", "Aucune pollution (tout coupé)", "Sin contaminación (todo desactivado)");
        public static string Umw_MasterTip => Loc.T("Turns off all six pollution sources at once. Existing pollution then decays on its own.", "Schaltet alle sechs Verschmutzungsquellen auf einmal ab. Bestehende Verschmutzung baut sich danach selbst ab.", "Coupe d'un seul coup les six sources de pollution. La pollution existante se dissipe ensuite d'elle-même.", "Desactiva de golpe las seis fuentes de contaminación. La contaminación existente se disipa por sí sola después.");
        public static string Umw_StatusOff => Loc.T("Pollution OFF", "Verschmutzung AUS", "Pollution COUPÉE", "Contaminación DESACTIVADA");
        public static string Umw_StatusNormal => Loc.T("Pollution normal", "Verschmutzung normal", "Pollution normale", "Contaminación normal");
        public static string Umw_TitleHousing => Loc.T("Settlement waste", "Siedlungs-Abfall", "Déchets des colonies", "Residuos de asentamientos");
        public static string Umw_NoWaste => Loc.T("No municipal waste", "Kein Hausmüll", "Aucun déchet municipal", "Sin residuos municipales");
        public static string Umw_NoWasteTip => Loc.T("Settlements no longer produce municipal waste (landfill).", "Siedlungen erzeugen keinen Hausmüll (Deponie) mehr.", "Les colonies ne produisent plus de déchets municipaux (décharge).", "Los asentamientos ya no producen residuos municipales (vertedero).");
        public static string Umw_NoBiowaste => Loc.T("No biowaste", "Kein Biomüll", "Aucun biodéchet", "Sin biorresiduos");
        public static string Umw_NoBiowasteTip => Loc.T("Settlements no longer produce biowaste.", "Siedlungen erzeugen keinen Biomüll mehr.", "Les colonies ne produisent plus de biodéchets.", "Los asentamientos ya no producen biorresiduos.");

        // ---- Wlt ----
        public static string Wlt_TitleMap => Loc.T("Map", "Karte", "Carte", "Mapa");
        public static string Wlt_TitleMines => Loc.T("World Mines", "Welt-Minen", "Mines du monde", "Minas mundiales");
        public static string Wlt_TitleTrade => Loc.T("Trade", "Handel", "Commerce", "Comercio");
        public static string Wlt_UnlimitedMines => Loc.T("Unlimited world mines", "Unbegrenzte Welt-Minen", "Mines du monde illimitées", "Minas mundiales ilimitadas");
        public static string Wlt_UnlimitedMinesTip => Loc.T("World mine deposits no longer deplete.", "Welt-Minen-Vorkommen erschöpfen nicht mehr.", "Les gisements des mines du monde ne s'épuisent plus.", "Los yacimientos de las minas mundiales ya no se agotan.");
        public static string Wlt_MinesNoUnity => Loc.T("Run world mines without Unity", "Welt-Minen ohne Unity betreiben", "Exploiter les mines du monde sans Unity", "Operar minas mundiales sin Unity");
        public static string Wlt_MinesNoUnityTip => Loc.T("World mines operate without consuming Unity.", "Welt-Minen laufen, ohne Unity zu verbrauchen.", "Les mines du monde fonctionnent sans consommer d'Unity.", "Las minas mundiales funcionan sin consumir Unity.");
        public static string Wlt_MinesEffMax => Loc.T("Max world mine efficiency", "Welt-Minen-Effizienz max", "Efficacité des mines du monde max", "Eficiencia máx. de minas mundiales");
        public static string Wlt_MinesEffMaxTip => Loc.T("Significantly increases the output of world mines.", "Erhöht die Förderleistung der Welt-Minen deutlich.", "Augmente nettement le rendement d'extraction des mines du monde.", "Aumenta considerablemente el rendimiento de extracción de las minas mundiales.");
        public static string Wlt_TradeBoost => Loc.T("Boost trade", "Handel boosten", "Booster le commerce", "Potenciar comercio");
        public static string Wlt_TradeBoostTip => Loc.T("More trade volume and contract profit; contracts no longer cost Unity.", "Mehr Handelsvolumen und Kontrakt-Gewinn; Kontrakte kosten keine Unity mehr.", "Plus de volume commercial et de gain sur les contrats ; les contrats ne coûtent plus d'Unity.", "Más volumen de comercio y beneficio por contrato; los contratos ya no cuestan Unity.");
        public static string Wlt_RevealMap => Loc.T("Reveal entire map", "Ganze Karte aufdecken", "Révéler toute la carte", "Revelar todo el mapa");
        public static string Wlt_RevealMapTip => Loc.T("Reveals the entire world map and resolves all world entities.", "Deckt die gesamte Weltkarte auf und löst alle Welt-Entitäten auf.", "Révèle l'intégralité de la carte du monde et découvre toutes les entités du monde.", "Revela todo el mapa mundial y descubre todas las entidades del mundo.");
        public static string Wlt_StatusRevealed => Loc.T("World map fully revealed", "Weltkarte komplett aufgedeckt", "Carte du monde entièrement révélée", "Mapa mundial revelado por completo");

        // ---- Wrf ----
        public static string Wrf_TitleShip => Loc.T("World Ship (Fleet)", "Welt-Schiff (Flotte)", "Navire du monde (flotte)", "Barco mundial (flota)");
        public static string Wrf_ForceUnload => Loc.T("Force-unload ship", "Schiff zwangsentladen", "Décharger le navire de force", "Forzar descarga del barco");
        public static string Wrf_ForceUnloadTip => Loc.T("Instantly unloads the world ship's entire cargo into its assigned shipyard.", "Entlädt die gesamte Fracht des Welt-Schiffs sofort in seine zugewiesene Werft.", "Décharge instantanément toute la cargaison du navire du monde dans son chantier naval affecté.", "Descarga al instante toda la carga del barco mundial en su astillero asignado.");
        public static string Wrf_FinishExploration => Loc.T("Finish exploration", "Exploration abschließen", "Terminer l'exploration", "Completar exploración");
        public static string Wrf_FinishExplorationTip => Loc.T("Instantly ends the ongoing exploration of the current map location.", "Beendet die laufende Erkundung der aktuellen Karten-Position sofort.", "Termine instantanément l'exploration en cours de la position actuelle sur la carte.", "Finaliza al instante la exploración en curso de la posición actual del mapa.");
        public static string Wrf_Repair => Loc.T("Repair ship", "Schiff reparieren", "Réparer le navire", "Reparar barco");
        public static string Wrf_RepairTip => Loc.T("Instantly repairs the world ship (fleet) to full health.", "Repariert das Welt-Schiff (Flotte) sofort auf volle Lebenspunkte.", "Répare instantanément le navire du monde (flotte) à pleins points de vie.", "Repara al instante el barco mundial (flota) hasta sus puntos de vida máximos.");
        public static string Wrf_StatusRepaired => Loc.T("Ship repaired", "Schiff repariert", "Navire réparé", "Barco reparado");
        public static string Wrf_TitleShips => Loc.T("Ships", "Schiffe", "Navires", "Barcos");
        public static string Wrf_ShipsFuel => Loc.T("Disable ship fuel consumption", "Schiffs-Treibstoff abschalten", "Couper la consommation des navires", "Desactivar consumo de barcos");
        public static string Wrf_ShipsFuelTip => Loc.T("All ships (world ship and cargo ships) no longer consume fuel.", "Alle Schiffe (Welt-Schiff und Frachtschiffe) verbrauchen keinen Treibstoff mehr.", "Tous les navires (navire du monde et navires cargo) ne consomment plus de carburant.", "Ningún barco (barco del mundo ni barcos de carga) consume ya combustible.");
        public static string Wrf_TitleCargo => Loc.T("Cargo ships (per type)", "Frachtschiffe (pro Typ)", "Navires cargo (par type)", "Barcos de carga (por tipo)");
        public static string Wrf_CargoShip => Loc.T("Cargo ship", "Frachtschiff", "Navire cargo", "Barco de carga");
        public static string Wrf_ShipInfo(object a0, object a1, object a2) => string.Format(Loc.T("{0} — Capacity: {1} % · Speed: {2}", "{0} — Kapazität: {1} % · Speed: {2}", "{0} — Capacité : {1} % · Vitesse : {2}", "{0} — Capacidad: {1} % · Velocidad: {2}"), a0, a1, a2);
        public static string Wrf_ShipResetTip => Loc.T("Resets capacity and speed of the selected cargo ship to default.", "Setzt Kapazität und Geschwindigkeit des gewählten Frachtschiffs auf den Standard zurück.", "Réinitialise la capacité et la vitesse du navire cargo sélectionné.", "Restablece la capacidad y velocidad del barco de carga seleccionado.");
        public static string Wrf_NoShips => Loc.T("(no cargo ships available)", "(keine Frachtschiffe vorhanden)", "(aucun navire cargo disponible)", "(no hay barcos de carga)");
        public static string Wrf_StatusShipCap(object a0, object a1) => string.Format(Loc.T("Cargo ship capacity {0} = x{1}", "Frachtschiff-Kapazität {0} = x{1}", "Capacité du navire {0} = x{1}", "Capacidad del barco {0} = x{1}"), a0, a1);
        public static string Wrf_StatusShipReset => Loc.T("Cargo ship reset", "Frachtschiff zurückgesetzt", "Navire cargo réinitialisé", "Barco de carga restablecido");
        public static string Wrf_TitleShipyard => Loc.T("Shipyard storage", "Werft-Lager", "Stockage du chantier naval", "Almacén del astillero");
        public static string Wrf_ShipyardCapInfo(object a0) => string.Format(Loc.T("Storage capacity: {0}", "Lager-Kapazität: {0}", "Capacité de stockage : {0}", "Capacidad de almacenamiento: {0}"), a0);
        public static string Wrf_ShipyardCapTip => Loc.T("Scales the storage capacity of all shipyard tiers.", "Skaliert die Lager-Kapazität aller Werft-Stufen.", "Met à l'échelle la capacité de stockage de tous les niveaux de chantier naval.", "Escala la capacidad de almacenamiento de todos los niveles del astillero.");
        public static string Wrf_DestroyCargo => Loc.T("Destroy shipyard cargo", "Werft-Fracht zerstören", "Détruire la cargaison du chantier", "Destruir carga del astillero");
        public static string Wrf_DestroyCargoTip => Loc.T("Discards all cargo held in the shipyard storage.", "Verwirft die gesamte im Werft-Lager liegende Fracht.", "Rejette toute la cargaison stockée dans le chantier naval.", "Descarta toda la carga almacenada en el astillero.");
        public static string Wrf_DumpCargo => Loc.T("Dump cargo to base storage", "Fracht ins Basis-Lager", "Verser la cargaison au stockage de base", "Volcar carga al almacén base");
        public static string Wrf_DumpCargoTip => Loc.T("Moves shipyard cargo into the global base storage.", "Legt die Werft-Fracht ins globale Basis-Lager.", "Déplace la cargaison du chantier vers le stockage de base global.", "Traslada la carga del astillero al almacén base global.");
        public static string Wrf_StatusShipyardCap(object a0) => string.Format(Loc.T("Shipyard capacity x{0}", "Werft-Kapazität x{0}", "Capacité du chantier x{0}", "Capacidad del astillero x{0}"), a0);
        public static string Wrf_StatusShipyardReset => Loc.T("Shipyard capacity reset", "Werft-Kapazität zurückgesetzt", "Capacité du chantier réinitialisée", "Capacidad del astillero restablecida");
        public static string Wrf_StatusCargoDestroyed => Loc.T("Shipyard cargo destroyed", "Werft-Fracht zerstört", "Cargaison du chantier détruite", "Carga del astillero destruida");
        public static string Wrf_StatusCargoDumped => Loc.T("Cargo moved to base storage", "Fracht ins Basis-Lager gelegt", "Cargaison déplacée au stockage de base", "Carga trasladada al almacén base");

        // ---- Tab ----
        public static string Tab_Produktion => Loc.T("Production", "Produktion", "Production", "Producción");

        // ---- Prod ----
        public static string Prod_TitleYield => Loc.T("Extraction & Yield", "Förderung & Ertrag", "Extraction & rendement", "Extracción y rendimiento");
        public static string Prod_Mining => Loc.T("Mining output ×10", "Förderleistung ×10", "Extraction ×10", "Extracción ×10");
        public static string Prod_MiningTip => Loc.T("Boosts the output of mines and pumps tenfold.", "Erhöht die Förderleistung von Bergwerken und Pumpen auf das Zehnfache.", "Multiplie par dix le rendement des mines et des pompes.", "Multiplica por diez el rendimiento de minas y bombas.");
        public static string Prod_Farm => Loc.T("Farm yield ×10", "Farm-Ertrag ×10", "Rendement agricole ×10", "Rendimiento agrícola ×10");
        public static string Prod_FarmTip => Loc.T("Multiplies farm harvest yield tenfold.", "Verzehnfacht den Ernteertrag von Farmen.", "Multiplie par dix le rendement des récoltes.", "Multiplica por diez la cosecha de las granjas.");
        public static string Prod_Solar => Loc.T("Solar output ×10", "Solar-Ertrag ×10", "Rendement solaire ×10", "Rendimiento solar ×10");
        public static string Prod_SolarTip => Loc.T("Multiplies solar panel power output tenfold.", "Verzehnfacht den Stromertrag von Solarpaneelen.", "Multiplie par dix la production des panneaux solaires.", "Multiplica por diez la producción de los paneles solares.");
        public static string Prod_TitleMachines => Loc.T("Machines", "Maschinen", "Machines", "Máquinas");
        public static string Prod_ForceRun => Loc.T("Force-run all machines", "Alle Maschinen zwangslaufen", "Forcer toutes les machines", "Forzar todas las máquinas");
        public static string Prod_ForceRunTip => Loc.T("Forces all machines to run even when they would otherwise pause.", "Erzwingt den Betrieb aller Maschinen, auch wenn sie sonst pausieren würden.", "Force toutes les machines à tourner même si elles s'arrêteraient normalement.", "Fuerza el funcionamiento de todas las máquinas aunque normalmente se detendrían.");
        public static string Prod_TitleReserves => Loc.T("Reserves", "Reserven", "Réserves", "Reservas");
        public static string Prod_UnlimitedWater => Loc.T("Unlimited groundwater", "Unerschöpfliches Grundwasser", "Nappe phréatique infinie", "Aguas subterráneas infinitas");
        public static string Prod_UnlimitedWaterTip => Loc.T("Groundwater deposits no longer deplete — pumps keep extracting indefinitely.", "Grundwasser-Vorkommen erschöpfen nicht mehr — Pumpen fördern dauerhaft weiter.", "Les nappes phréatiques ne s'épuisent plus — les pompes continuent indéfiniment.", "Las aguas subterráneas ya no se agotan — las bombas siguen extrayendo indefinidamente.");
        public static string Prod_NoOilDrain => Loc.T("No oil drain", "Kein Erdöl-Verbrauch", "Pas de consommation de pétrole", "Sin consumo de petróleo");
        public static string Prod_NoOilDrainTip => Loc.T("Oil deposits are refilled to capacity every day.", "Erdöl-Vorkommen werden täglich wieder auf Kapazität aufgefüllt.", "Les gisements de pétrole sont remplis à pleine capacité chaque jour.", "Los yacimientos de petróleo se rellenan a su capacidad cada día.");

        // ---- Wet ----
        public static string Wet_TitleFix => Loc.T("Lock Weather Permanently", "Wetter dauerhaft fixieren", "Fixer la météo en permanence", "Fijar el clima de forma permanente");
        public static string Wet_TitleCycle => Loc.T("Natural Cycle", "Natürlicher Zyklus", "Cycle naturel", "Ciclo natural");
        public static string Wet_Sunny => Loc.T("Sunny", "Sonnig", "Ensoleillé", "Soleado");
        public static string Wet_Cloudy => Loc.T("Cloudy", "Bewölkt", "Nuageux", "Nublado");
        public static string Wet_Rainy => Loc.T("Rain", "Regen", "Pluie", "Lluvia");
        public static string Wet_HeavyRain => Loc.T("Heavy Rain", "Starkregen", "Forte pluie", "Diluvio");
        public static string Wet_ResetTip => Loc.T("Lifts the weather lock and releases the natural weather cycle again.", "Hebt die Wetter-Fixierung auf und gibt den natürlichen Wetterzyklus wieder frei.", "Annule la fixation de la météo et rétablit le cycle météo naturel.", "Anula el clima fijado y vuelve a habilitar el ciclo natural del clima.");
        public static string Wet_StatusSunny => Loc.T("Weather locked: Sunny", "Wetter fixiert: Sonnig", "Météo fixée : ensoleillé", "Clima fijado: Soleado");
        public static string Wet_StatusCloudy => Loc.T("Weather locked: Cloudy", "Wetter fixiert: Bewölkt", "Météo fixée : nuageux", "Clima fijado: Nublado");
        public static string Wet_StatusRainy => Loc.T("Weather locked: Rain", "Wetter fixiert: Regen", "Météo fixée : pluie", "Clima fijado: Lluvia");
        public static string Wet_StatusHeavyRain => Loc.T("Weather locked: Heavy Rain", "Wetter fixiert: Starkregen", "Météo fixée : forte pluie", "Clima fijado: Diluvio");
        public static string Wet_StatusReset => Loc.T("Weather reset (natural cycle)", "Wetter zurückgesetzt (natürlicher Zyklus)", "Météo réinitialisée (cycle naturel)", "Clima restablecido (ciclo natural)");

        // ---- Prf ----
        public static string Prf_TitleSafety => Loc.T("Safety", "Sicherheit", "Sécurité", "Seguridad");
        public static string Prf_TitleProfile => Loc.T("Cheat Profile", "Cheat-Profil", "Profil de triche", "Perfil de trucos");
        public static string Prf_TitlePresets => Loc.T("Preset Slots", "Preset-Slots", "Emplacements de préréglages", "Ranuras de preajuste");
        public static string Prf_PanicOff => Loc.T("Panic Off (all persistent cheats off)", "Panik-Aus (alle Dauer-Cheats aus)", "Arrêt panique (tous les cheats permanents coupés)", "Apagado de pánico (desactiva todos los trucos permanentes)");
        public static string Prf_PanicOffTip => Loc.T("Turns off ALL running persistent cheats in one go and sets speed to 1x.", "Schaltet auf einen Schlag ALLE laufenden Dauer-Cheats ab und setzt die Geschwindigkeit auf 1x.", "Coupe d'un seul coup TOUS les cheats permanents en cours et remet la vitesse sur 1x.", "Desactiva de golpe TODOS los trucos permanentes activos y pone la velocidad en 1x.");
        public static string Prf_SlotSave(object a0) => string.Format(Loc.T("Save slot {0}", "Slot {0} speichern", "Enregistrer l'emplacement {0}", "Guardar en ranura {0}"), a0);
        public static string Prf_SlotSaveTip => Loc.T("Saves the current persistent-cheat state to this slot.", "Speichert den aktuellen Dauer-Cheat-Zustand in diesen Slot.", "Enregistre l'état actuel des cheats permanents dans cet emplacement.", "Guarda en esta ranura el estado actual de los trucos permanentes.");
        public static string Prf_SlotLoad(object a0) => string.Format(Loc.T("Load slot {0}", "Slot {0} laden", "Charger l'emplacement {0}", "Cargar ranura {0}"), a0);
        public static string Prf_SlotLoadTip => Loc.T("Applies the state saved in this slot.", "Wendet den in diesem Slot gespeicherten Zustand an.", "Applique l'état enregistré dans cet emplacement.", "Aplica el estado guardado en esta ranura.");
        public static string Prf_AutoRestore => Loc.T("Auto-restore on load", "Auto-Restore beim Laden", "Restauration auto au chargement", "Restaurar automáticamente al cargar");
        public static string Prf_AutoRestoreTip => Loc.T("Automatically applies the last saved cheat state when the menu is opened after loading a save.", "Wendet den zuletzt gespeicherten Cheat-Zustand beim Öffnen des Menüs nach einem Spielstand-Laden automatisch an.", "Applique automatiquement le dernier état de cheats enregistré à l'ouverture du menu après le chargement d'une sauvegarde.", "Aplica automáticamente el último estado de trucos guardado al abrir el menú tras cargar una partida.");
        public static string Prf_SaveState => Loc.T("Save state", "Zustand speichern", "Enregistrer l'état", "Guardar estado");
        public static string Prf_SaveStateTip => Loc.T("Remembers all currently active persistent cheats (for auto-restore and manual restore).", "Merkt sich alle aktuell aktiven Dauer-Cheats (für Auto-Restore und manuelles Wiederherstellen).", "Mémorise tous les cheats permanents actuellement actifs (pour la restauration auto et manuelle).", "Recuerda todos los trucos permanentes activos (para restaurar automática o manualmente).");
        public static string Prf_RestoreState => Loc.T("Restore state", "Zustand wiederherstellen", "Restaurer l'état", "Restaurar estado");
        public static string Prf_RestoreStateTip => Loc.T("Instantly applies the last saved cheat state.", "Wendet den zuletzt gespeicherten Cheat-Zustand sofort an.", "Applique instantanément le dernier état de cheats enregistré.", "Aplica al instante el último estado de trucos guardado.");
        public static string Prf_StatusPanic => Loc.T("All persistent cheats turned off", "Alle Dauer-Cheats abgeschaltet", "Tous les cheats permanents coupés", "Todos los trucos permanentes desactivados");
        public static string Prf_StatusSlotSaved(object a0) => string.Format(Loc.T("Preset slot {0} saved", "Preset-Slot {0} gespeichert", "Emplacement de préréglage {0} enregistré", "Ranura de preajuste {0} guardada"), a0);
        public static string Prf_StatusSlotLoaded(object a0) => string.Format(Loc.T("Preset slot {0} loaded", "Preset-Slot {0} geladen", "Emplacement de préréglage {0} chargé", "Ranura de preajuste {0} cargada"), a0);
        public static string Prf_StatusSlotEmpty(object a0) => string.Format(Loc.T("Preset slot {0} is empty", "Preset-Slot {0} ist leer", "L'emplacement de préréglage {0} est vide", "La ranura de preajuste {0} está vacía"), a0);
        public static string Prf_StatusAutoRestoreOn => Loc.T("Auto-restore ON", "Auto-Restore AN", "Restauration auto ACTIVÉE", "Restauración automática ACTIVADA");
        public static string Prf_StatusAutoRestoreOff => Loc.T("Auto-restore OFF", "Auto-Restore AUS", "Restauration auto DÉSACTIVÉE", "Restauración automática DESACTIVADA");
        public static string Prf_StatusStateSaved => Loc.T("Current cheat state saved", "Aktueller Cheat-Zustand gespeichert", "État actuel des cheats enregistré", "Estado actual de trucos guardado");
        public static string Prf_StatusStateApplied => Loc.T("Saved cheat state applied", "Gespeicherter Cheat-Zustand angewendet", "État de cheats enregistré appliqué", "Estado de trucos guardado aplicado");

        // ---- Ctrl ----
        public static string Ctrl_StatusAutoRestored => Loc.T("Saved cheat state restored", "Gespeicherter Cheat-Zustand wiederhergestellt", "État de cheats enregistré restauré", "Estado de trucos guardado restaurado");

        // ---- Wand ----
        public static string Wand_ShipyardFueled(object a0) => string.Format(Loc.T("Shipyard {0}: fully fueled", "Werft {0}: vollgetankt", "Chantier naval {0} : ravitaillé", "Astillero {0}: repostado al completo"), a0);
        public static string Wand_ShipyardUnavail(object a0) => string.Format(Loc.T("Shipyard {0}: refuel not available", "Werft {0}: Volltanken nicht verfügbar", "Chantier naval {0} : ravitaillement indisponible", "Astillero {0}: repostaje completo no disponible"), a0);
        public static string Wand_DepotFueled(object a0) => string.Format(Loc.T("Cargo depot {0}: fully fueled", "Cargo-Depot {0}: vollgetankt", "Dépôt de fret {0} : ravitaillé", "Depósito de carga {0}: repostado al completo"), a0);
        public static string Wand_DepotUnavail(object a0) => string.Format(Loc.T("Cargo depot {0}: refuel not available", "Cargo-Depot {0}: Volltanken nicht verfügbar", "Dépôt de fret {0} : ravitaillement indisponible", "Depósito de carga {0}: repostaje completo no disponible"), a0);
        public static string Wand_VehicleFueled(object a0) => string.Format(Loc.T("Vehicle {0}: fully fueled", "Fahrzeug {0}: vollgetankt", "Véhicule {0} : ravitaillé", "Vehículo {0}: repostado al completo"), a0);
        public static string Wand_VehicleNoTank(object a0) => string.Format(Loc.T("Vehicle {0}: no tank", "Fahrzeug {0}: kein Tank", "Véhicule {0} : pas de réservoir", "Vehículo {0}: sin depósito"), a0);
        public static string Wand_StorageEmptied(object a0) => string.Format(Loc.T("Storage {0}: emptied", "Lager {0}: geleert", "Stockage {0} : vidé", "Almacén {0}: vaciado"), a0);
        public static string Wand_StorageNormal(object a0) => string.Format(Loc.T("Storage {0}: normal (cheat OFF)", "Lager {0}: normal (Cheat AUS)", "Stockage {0} : normal (cheat OFF)", "Almacén {0}: normal (truco DESACTIVADO)"), a0);
        public static string Wand_StorageGodOn(object a0) => string.Format(Loc.T("Storage {0}: god mode ON (supplies infinitely)", "Lager {0}: Gott-Modus AN (liefert unendlich)", "Stockage {0} : mode dieu ACTIVÉ (fournit à l'infini)", "Almacén {0}: modo dios ACTIVADO (suministro infinito)"), a0);
    }
}
